# Generated by Django 5.1.3 on 2024-12-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='created_by',
        ),
    ]
