# Generated by Django 5.1.3 on 2024-12-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(related_name='tasks', to='todo_list.project'),
        ),
    ]
