# Generated by Django 5.1.3 on 2024-12-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_owner'),
        ('todo_list', '0004_task_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.team'),
        ),
    ]
